#!/usr/bin/env python3
"""
Seed prod Firestore with candidates, parties, electoral lists, and municipalities.

Reads from the dev seed JSON files (generated by generate_seed_from_csv.py)
which already include municipality_code and party_ids (from nuance mapping).

Incremental: only writes documents that are new or changed (skips existing ones).

Usage:
    GOOGLE_APPLICATION_CREDENTIALS=~/Downloads/chat-vote-prod-firebase-adminsdk-fbsvc-*.json \
    python3 scripts/seed_prod_firestore.py [--dry-run] [--force]
"""

import json
import logging
import os
import sys
from pathlib import Path

import firebase_admin
from firebase_admin import credentials, firestore

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger(__name__)

SEED_DIR = Path(__file__).resolve().parents[1] / "firebase" / "firestore_data" / "dev"


def _docs_equal(existing: dict, new: dict) -> bool:
    """Check if existing Firestore doc matches new seed data (ignoring extra fields in Firestore)."""
    for key, value in new.items():
        if existing.get(key) != value:
            return False
    return True


def _seed_collection(db, collection: str, data: dict, dry_run: bool, force: bool) -> tuple[int, int]:
    """Seed a Firestore collection incrementally. Returns (written, skipped)."""
    written = 0
    skipped = 0

    if not force:
        # Fetch existing docs in one batch
        existing = {}
        for doc in db.collection(collection).stream():
            existing[doc.id] = doc.to_dict()
        logger.info(f"  {collection}: {len(existing)} existing docs in Firestore")
    else:
        existing = {}

    for doc_id, doc_data in sorted(data.items()):
        if not force and doc_id in existing and _docs_equal(existing[doc_id], doc_data):
            skipped += 1
            continue

        if dry_run:
            action = "UPDATE" if doc_id in existing else "CREATE"
            logger.info(f"  [DRY RUN] {action} {collection}/{doc_id}")
        else:
            db.collection(collection).document(doc_id).set(doc_data, merge=True)
        written += 1

    return written, skipped


def seed_prod_firestore(dry_run: bool = False, force: bool = False):
    cred_path = os.environ.get("GOOGLE_APPLICATION_CREDENTIALS")
    if not cred_path:
        logger.error("GOOGLE_APPLICATION_CREDENTIALS not set")
        sys.exit(1)

    cred = credentials.Certificate(cred_path)
    app = firebase_admin.initialize_app(cred)
    db = firestore.client()
    logger.info(f"Connected to Firebase project: {app.project_id}")

    # Load seed data
    with open(SEED_DIR / "candidates.json") as f:
        candidates = json.load(f)
    with open(SEED_DIR / "electoral_lists.json") as f:
        electoral_lists = json.load(f)
    with open(SEED_DIR / "municipalities.json") as f:
        municipalities = json.load(f)
    parties_path = SEED_DIR / "parties.json"
    parties = json.load(open(parties_path)) if parties_path.exists() else {}

    with_party = sum(1 for c in candidates.values() if c.get("party_ids"))
    logger.info(
        f"Seed data: {len(candidates)} candidates ({with_party} with party_ids), "
        f"{len(electoral_lists)} electoral lists, {len(municipalities)} municipalities, {len(parties)} parties"
    )

    if force:
        logger.info("--force: writing all documents regardless of existing state")

    # Seed each collection
    for name, data in [
        ("parties", parties),
        ("candidates", candidates),
        ("electoral_lists", electoral_lists),
        ("municipalities", municipalities),
    ]:
        if not data:
            continue
        logger.info(f"Seeding {name}...")
        written, skipped = _seed_collection(db, name, data, dry_run, force)
        logger.info(f"  {name}: {written} written, {skipped} skipped (unchanged)")

    logger.info("Done!")


if __name__ == "__main__":
    dry_run = "--dry-run" in sys.argv
    force = "--force" in sys.argv
    seed_prod_firestore(dry_run=dry_run, force=force)
